# Generated by Django 5.0.4 on 2024-04-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stars', models.CharField(choices=[(1, 'Terrible'), (2, 'Poor'), (3, 'Average'), (4, 'Very Good'), (5, 'Excellent')], default='Average', max_length=255)),
                ('price_per_night', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(choices=[('TR', 'tropical'), ('AL', 'Alpine'), ('OC', 'Oceanic'), ('CN', 'Continental')], default='Continental', max_length=255)),
                ('country', models.ManyToManyField(related_name='climates', to='touragency.country')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.CharField(choices=[(1, 'One week'), (2, 'Two weeks'), (4, 'Four weeks')], max_length=255)),
                ('departure_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='touragency.country')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='touragency.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='touragency.tour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='touragency.user')),
            ],
        ),
    ]
