# Generated by Django 5.0.4 on 2024-04-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0002_alter_user_options_alter_user_managers_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('staff', 'staff'), ('client', 'client')], default='client', max_length=255, null=True),
        ),
    ]
