# Generated by Django 5.0.4 on 2024-04-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(default=123, editable=False),
            preserve_default=False,
        ),
    ]
