# Generated by Django 5.0.4 on 2024-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0004_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
