# Generated by Django 5.0.4 on 2024-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0005_alter_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(choices=[(1, 'One week'), (2, 'Two weeks'), (4, 'Four weeks')]),
        ),
    ]
