# Generated by Django 5.0.4 on 2024-04-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0007_remove_tour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
