# Generated by Django 5.0.4 on 2024-04-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0009_alter_tour_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
    ]
