# Generated by Django 5.0.4 on 2024-04-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0011_tour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=123, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('staff', 'staff'), ('client', 'client')], default='client', max_length=6),
        ),
    ]
